<?php
if ( !function_exists( 'add_action' ) ) {
	if ( !headers_sent() ) { header('HTTP/1.1 403 Forbidden'); }
	die('ERROR: This plugin requires WordPress and will not function if called directly.');
	}

function spamshield_get_anchortxt_blacklist() {
	$blacklist_keyphrases = array( // 1158
		"1 night stand", "1 nite stand", "2013", "2014", "2015", "3 way", "3 way link", "ability", "absolutely", "access", "accident", "account", "accountant", "accounting", "accutane", "acomplia", "acquire", 
		"action", "acupunture", "additional", "address", "adipex", "administration", "adult", "adult chat", "adventure", "advertise", "advertising", "advice", "affiliate", "affliction", "affordable", "african", 
		"agency", "air jordan", "alabama", "alarm system", "alaska", "allied", "alprostadil", "amateur", "amature", "amazon", "ambassador", "ambien", "anabolic", "analysis", "anchor", "android", "anglomania", 
		"annual", "anonymous", "answer", "antler", "anxiety", "apartment", "appliance", "application", "arcane", "architecture", "arctic", "argent", "arizona", "arkansas", "arterial", "asphalt", "assistant", 
		"attack", "attorney", "auction", "aumento", "australian", "authentic", "availability", "available", "avanafil", "avenue", "average", "aviation", "aviator", "baccarrat", "bagatelle", "balance", "bamboo", 
		"bandage", "bankruptcy", "baratos", "baseball", "basement", "basketball", "battery", "bed bug", "bedding", "bedroom", "beginner", "behavior", "benefit", "bespoke", "bestiality", "betting", "biggest", 
		"birthday", "bisexual", "blackjack", "bleeding", "blogging", "blogspot", "blow job", "bluetooth", "booster", "booty call", "boulder", "boutique", "bracelet", "brazilian", "breast", "bridal", "brigade", 
		"brooch", "browse", "bucuresti", "builder", "building", "bungalow", "burnisher", "business", "buy pill", "cabinet", "caffeine", "calculator", "calendar", "california", "calipers", "call girl", "cambogia", 
		"cannabis", "canvas", "capital", "capture", "car rental", "career", "carisoprodol", "cash advance", "cashmere", "casinos", "casque", "casual", "caterer", "caught", "celebrity", "cellulite", "celulit", 
		"century", "certificate", "certify", "challenge", "chat room", "chateau", "chaturbate", "chaussure", "cheap", "cheat", "chicago", "chicken", "children", "chiropractic", "chiropractor", "chronograph", 
		"cialis", "cigarette", "citrate", "classic", "cleaning", "cleanse", "clear-cut", "clearance", "click here", "click the", "click through", "clinic", "clinical", "clitoris", "clonazepam", "clothes", 
		"clothing", "clutch", "cockroach", "cockroaches", "collection", "college student", "collision", "cologne", "comfortable", "coming", "command", "comment poster", "commentator", "comments", "commercial", 
		"commission", "community", "compact", "compagnie", "company", "compass", "compilation", "compose", "compressed", "compression", "compressor", "computer", "concentrate", "concrete", "condition", 
		"conditioning", "configure", "connecticut", "conservative", "consider", "consolidation", "constructeur", "construction", "consultant", "consulting", "consumption", "contact", "container", "content", 
		"contracting", "contractor", "control", "controversy", "convoy", "cooling", "corporate", "cosmetic", "cougar", "counseling", "country", "county", "coupon", "crack", "creator", "credit card", "credit report", 
		"credits", "crescent", "criminal", "crimson", "critical", "cruiser", "crusher", "cuisine", "cum", "cum shot", "cumulus", "curtain", "custom", "customer", "cutlery", "cyclen", "cyclobenzaprine", 
		"dailymotion", "dapoxetine", "dating", "daughter", "deals", "deduction", "defense", "definition", "delivery", "dental", "dentist", "deodorant", "deposit", "depreciation", "depression", "dermatologist", 
		"descent", "desert", "design", "desnuda", "despicable", "detector", "detroit", "deutschland", "development", "diagram", "dictator", "diet pill", "diets", "difference", "different", "digital", "dildo", 
		"diminish", "directly", "directory", "discipline", "discount", "discreet", "disfuncao", "dispensary", "dissertation", "dividing", "divorce", "domain", "dosage", "download", "drawer", "drawing", "dresses", 
		"dribble", "drug rehab", "drying", "dui lawyer", "dungeon", "durable", "duty free", "dutyfree", "dysfunction", "e-learning", "e-site", "earn money", "economic", "edition", "edmonton", "educational", 
		"effect", "ejaculate", "electrician", "electronic", "elixir", "email list", "emergency", "empire", "employment", "enclosure", "energy", "engagement", "engine", "engineer", "engrossar", "enhancement", 
		"enlarged", "enlargement", "enterprise", "entertaining", "entertainment", "enthusiasm", "ephedra", "ephedrine", "equity", "equity loan", "erectile", "erection", "eretil", "erotic", "eroticism", 
		"erythromycin", "escort service", "escorts", "especial", "estate", "etoile", "european", "evasion", "evening", "evolution", "example", "exclusive", "executive", "exercise", "exodus", "expedition", 
		"experimental", "expert", "exterminating", "extermination", "exterminator", "extract", "extreme", "eyeglasses", "fabric", "facebook", "facial", "factory", "faculty", "failure", "family", "famous", "fasix", 
		"fat loss", "female", "feminine", "filing", "finance", "financial", "finding", "finishing", "fioricet", "fitness", "flagstaff", "flooring", "follow", "follower", "following", "football", "for sale", 
		"foreclosure", "foreign", "forever", "forex", "forgetfulness", "formal", "formula", "fort worth", "forum", "foulard", "free code", "freenet", "frontier", "frozen", "fuck", "fuckbuddy", "fuckin", 
		"fundamental", "funeral", "fungal", "furniture", "galaxy", "gambling", "gambling online", "gaming", "garcinia", "garcinia cambogia", "generate", "generation", "generator", "generic", "genesis", "get rid of", 
		"glazing", "government", "gratis", "gratuit", "green coffee", "green tea", "growth", "guarantee", "guarded", "gynecologist", "gynecology", "hack wifi", "hackear", "hair loss", "hand bag", "handbook", 
		"handle", "happen", "hardware", "hawaii", "health", "health care", "healthy", "hearthstone", "heating", "heavenly", "hentai", "herbalife", "herpes", "herself", "heterosexual", "hip hop", "history", 
		"hitherto", "holdem", "holdem poker", "holdem software", "home design", "home equity", "home finance", "homemade", "homeopathic", "homepage", "homosexual", "hormone", "horror", "hospital", "hosting", 
		"hotel", "hotel deal", "hotel e-site", "how to", "hydrocodone", "illinois", "imitation", "immediate", "implant", "important", "impotence", "impotencia", "impotent", "impound", "improve", "improvement", 
		"incest", "income", "independent", "india outsource", "indiana", "indianapolis", "indoor", "infant", "infection", "infestation", "infinity", "information", "inhibitor", "injection", "injury", 
		"injury lawyer", "injustice", "insert", "inspirational", "instagram", "installation", "installer", "instant", "instruct", "instructor", "instrumental", "insult", "insurance", "insurance deal", 
		"insurance quote", "intelligent", "interior", "international", "internet", "interview", "introduction", "invest", "investment", "investor", "irritable", "italian", "jacket", "jacksonville", "jailbreak", 
		"javascript", "jewellery", "jewelry", "jewish", "jockey", "johannesburg", "journalism", "junction", "jungle", "kangaroo", "kentucky", "keratin", "ketone", "keyword", "klonopin", "knives", "kroatien", 
		"kroatien insel brac", "labia", "labial", "labiale", "landlord", "language", "laptop", "laptopuri", "las vegas", "lattice", "launch", "leading", "lemonade", "lesbian", "leveling", "levelling", "levitra", 
		"levtira", "libido", "library", "lifeless", "lighting", "limited", "link builder", "link building", "linked in", "liquid", "livraison", "location", "locksmith", "logo design", "los angeles", "lose fat", 
		"lose weight", "losing", "lotion", "lottery", "louisiana", "louisville", "luggage", "lunette", "luxury", "lyric", "machine", "magazine", "magnificent", "make money", "making", "management", "manager", 
		"manteau", "manufacturer", "marijuana", "massachusetts", "massage", "masturbate", "material", "mature", "measuring", "mechanical", "medical", "medicament", "medication", "medium", "megapolis", "memphis", 
		"mercurial", "meridia", "message", "metallic", "michigan", "milf", "military", "minnesota", "minute", "mississippi", "missouri", "mistake", "mobilabonnement priser", "mobile", "modern", "modernity", 
		"modular", "modulesoft", "momentum", "money make", "monogram", "monster", "montaigne", "monthly", "montre", "mortal", "mortgage", "movable", "movie", "moving", "murder", "muscle", "muscular", "mustang", 
		"naked", "nashville", "natural", "naturally", "naughty", "nebraska", "necessity", "necklace", "negotiation", "network", "nevada", "new hampshire", "new jersey", "new mexico", "new york", "nike air", 
		"nike shoe", "nimbus", "north carolina", "north dakota", "notwithstanding", "novelty", "nude", "nudism", "numerology", "nursery", "ob-gyn", "obstetric", "obstetrician", "occasion", "office", "official", 
		"oklahoma", "one night stand", "one nite stand", "online", "online gambling", "online marketing", "opiate", "opponent", "optimization", "option", "ordering", "organic", "organization", "orgasm", "original", 
		"ottawa", "outdoor", "outfit", "outlet", "outsource india", "overnight", "oxymoron", "page rank", "pageant", "painless", "pantry", "particular", "password", "paternity", "pavilion", "paxil", "payday", 
		"pebbled", "penetracion", "penetrate", "peniana", "peniano", "penile", "penis", "pennsylvania", "percocet", "perfectly", "performance", "perfume", "period", "periodontist", "personal", "personality", 
		"personalization", "pest control", "petroleum", "phantom", "pharmacy", "phentermine", "philadelphia", "photoshop", "php expert", "phpdug", "phytoceramide", "pills", "pinterest", "pirate", "plague", 
		"plan cul", "plan q", "planet", "plantar fasciitis", "plastic", "platinum", "play", "playing", "plumbing", "poker", "poker chip", "policy", "politic", "political", "pompano", "popular", "population", "porn", 
		"porn star", "porno", "pornographic", "pornography", "porntube", "portable", "portemonnaie", "portfolio", "positive", "possible", "power kite", "poze", "practice", "pregnancy", "pregnant", "prelude", 
		"premature", "premium", "prepaid", "prescription", "press room", "pressure", "prestige", "prevent", "previous", "priligy", "primary", "princess", "printer", "prisoner", "privacy", "private", "product", 
		"production", "professional", "program", "programa", "programme", "project", "promo code", "promotion", "propane", "propecia", "property", "proportional", "prospect", "prostate", "prostitute", "protein", 
		"protocol", "proxy", "psychic", "publicity", "pulmonary", "purse", "pussy", "puzzle", "quartz", "quote", "racing", "ranking", "rapes", "raping", "rapist", "reaction", "read the", "realistic", "reality", 
		"realty", "recent", "recruiting", "rectangle", "redeem", "redsnow", "reduce", "reebok", "reference", "reflection", "reflective", "reflexion", "reflux", "refrigerator", "relate", "related", "release", 
		"religion", "reload", "removal", "remove", "rencontre", "renewal", "renovating", "renovation", "rent a car", "rental", "repair", "reparatii", "repellent", "replace", "replacement", "replica", "replicate", 
		"repossession", "reputation", "requin", "residence", "residential", "resilience", "resolve", "resource", "restaurant", "restoration", "restore", "result", "return", "revatio", "reverse", "reviews", 
		"rhinoplasty", "rhode island", "rimonabant", "ring tone", "ripped", "rivotril", "roaches", "roofer", "roofing", "router", "rubber", "runway", "safety", "san antonio", "san diego", "san francisco", 
		"san jose", "satellite", "saturday", "schedule", "search engine", "search marketing", "seattle", "secondary", "secret", "secure", "security", "segment", "sem", "seminar", "sempre", "sensible", "sensitive", 
		"seo", "septum", "series", "services", "sex", "sex drive", "sex tape", "sexcam", "sexe", "sexiness", "sexism", "sexologia", "sextant", "sexual", "sexual performance", "sexual service", "sexuality", "sexy", 
		"shades", "shampoo", "shemale", "shipping", "shoes", "shopping", "short-term loan", "shower", "showroom", "sildenafil", "simply", "simulation", "singing", "sister", "sizing", "skater", "skeleton", "sketch", 
		"skin care", "sleeve", "slot machine", "smoking", "sneaker", "soccer", "social", "social bookmark", "social media", "social poster", "social submitter", "society", "software", "solenoid", "solution", "soma", 
		"source", "south carolina", "south dakota", "special", "specific", "spence diamond", "spending", "spinal", "splashy", "spray tan", "stainless", "starcraft", "starting", "statement", "statistics", "staxyn", 
		"stendra", "steroid", "storify", "straightforward", "streaming", "student loan", "studio", "stylish", "submit", "submitter", "subway", "success", "sucking", "suggestion", "sunglass", "sunglasses", 
		"supplement", "supply", "support", "supreme", "surgeons", "surgery", "survey", "survival", "swatch", "sweating", "syndrome", "system", "tablet", "tactic", "tadalafil", "taille", "tanning", "tassel", 
		"tattoo", "technology", "template", "temporary", "tequila", "testosterone", "texas holdem", "thanksgiving", "therapy", "thousand", "three way", "three way link", "through", "title", "toddler", "toilette", 
		"top e-site", "top site", "tortoise", "tourist", "trackback", "tractor", "trading", "traditional", "traffic", "training", "tramadol", "transfer", "translate", "transportation", "travail", "travel", 
		"treatment", "trim spa", "trophy", "tropical", "troubleshoot", "troubleshooting", "turbo tax", "turnkey", "turquoise", "tutorial", "twitter", "tycoon", "ultimate", "ultram", "unblocked", "underground", 
		"underneath", "understanding", "underwear", "unique", "unisex", "united states", "university", "unlimited", "unlock", "uptown", "utility", "vacation", "vagina", "vaginal", "vainglory", "valium", "vancouver", 
		"vaporizer", "vardenafil", "various", "vehicle", "vendor", "ventilation", "veterinarian", "veterinary", "viagra", "video", "videography", "vigara", "vigrx", "village", "vintage", "vioxx", "virtual", 
		"vision", "visit", "visit now", "visite", "visual", "volume", "vortex", "voucher", "voyage", "warfare", "watches", "waterproof", "wayfarer", "wealth", "web host", "web hosting", "web page", "web site", 
		"webmaster", "weight loss", "weightless", "west virginia", "whirlpool", "whitening", "wholesale", "wicked", "wifi hack", "wifi hacker", "window", "wireless", "wisconsin", "work out", "wrestling", 
		"writing service", "wyoming", "xanax", "xenical", "xxx", "youtube", "zimulti", "zithromax", "zoekmachine optimalisatie", "zolus", 
		);
	return $blacklist_keyphrases;
	}

function spamshield_get_domain_blacklist() {
	$blacklist_domains = array( // 384
		"111things.com", "1ari.com", "21joannapaydayloanscompany.joannaloans.co.uk", "24hrdesign.com", "360webmarketing.com", "360webmarketing.net", "5starlogo.com", "accrinet.com", "actualseomedia.com", 
		"adult-poster.com", "advectors.com", "agenciade.serviciosdeseo.com", "agentbutler.com", "alkyonedigital.com", "androidappsprogramming.com", "appschopper.com", "appsgenies.com", "ar-kane.com", 
		"ardorcontent.com", "ardormediafactory.com", "ardorranking.com", "ardorseo.com", "arihantwebtech.com", "arisalomon.com", "articlewritinghelp.com", "artonius.hu", "asteor.com", "astior.com", 
		"autobacklinkservice.com", "autopostersoftware.com", "avention.com", "awbgenius.com", "bettergraph.com", "betterlinkadvertising.com", "billcollectionsagency.com", "binarysolutions.biz", "biz-lenders.com", 
		"bluebacklinks.com", "blyweertbeaufort.co.uk", "bosswebtech.com", "bpdominator.com", "burnleytaskforce.org.uk", "businesscardsutah.com", "buycontenthere.com", "buyhighprbacklink.biz", "callumcontent.com", 
		"canadianwarmbloods.com", "captainmarketing.com", "catamerica.com", "catbpo.com", "cattechnologies.biz", "cattechnologies.com", "cattechsoft.com", "cattinc.com", "ccls5280.org", "checkli.com", 
		"checklistpal.com", "chefsrecommend.com", "chicagob.com", "chicagoseoconsultants.com", "chicagoweb-design.com", "chrislonergan.co.uk", "cibol.net", "citrix.com", "cl-dominator.com", "click4pardeep.com", 
		"cnelindia.com", "commentposter.com", "consultmarvinrussell.com", "contentrunner.com", "crackfacebookaccount.com", "creativeforever.in", "crestseo.net", "cromosys.com", "crosslinkmarketing.com", 
		"csschopper.com", "cssclever.com", "cssprecise.com", "cyber-seo.com", "darwinlogic.com", "darwinlogic.net", "davaomedical.com", "designz23.com", "digitalexits.com", "disctoprint.co.uk", "dougthomas.biz", 
		"dreamforweb.com", "dreamsoftindia.com", "dreamsoftindia.net", "droa.com", "e-intelligence.in", "eagle-condor.org", "emailchopper.com", "empirecompanyusa.com", "entiver.com", "entiveracademy.com", 
		"expertory.com", "explainermagic.com", "explainmybusiness.com", "explodeseo.com", "explodeseo.devhub.com", "explodeseo.typepad.com", "explodeseo.us", "explodeseo.webnode.com", "explodeseo.yolasite.com", 
		"exponentialseo.net", "ezadblaster.com", "fabledesign.in", "fabletechnologies.com", "fabletechnologies.us", "facebookmarketingxtc.com", "fat-milf.com", "fish-instant-payday-loans.co.uk", "fivestarlogo.com", 
		"fosterseo.ca", "friendlybuilders.co.uk", "fuckyou.com", "fugenx.com", "futurestradingsecrets.com", "gardenersrecommend.com", "gelfree.com", "generalonlineservices.com", "get-online-business.com", 
		"getwicked.co.uk", "ghalichiglam.com", "globaldata4u.com", "gonextsolutions.com", "hazelnutfilms.com", "helloari.com", "helloarihosting.com", "heritagenorth.co.uk", "hhmla.ca", "hireitdevelopers.com", 
		"hirewordpressexperts.com", "hit4hit.org", "howtohypnotizesomeoneforbeginners.com", "humin.com", "hyperwebmarketing.org", "hypnosisforbeginners.com", "icls.net", "idea2psd.com", "ifline.com", 
		"imarketingphuket.com", "imediasolutions.biz", "immobilientechnologies.com", "incaltaminte-mopiel.ro", "increaseorganicsales.com", "increaseorganicsales.in", "insiderbeer.com", "insiderswine.com", 
		"insiderswinereport.com", "insiderwinereport.com", "intag.co", "integritywinereport.com", "internetmarketingexpertz.com", "internetmarketingxtc.com", "internetsearchenginepros.com", "inventivewebtrack.com", 
		"iotwebsolutions.com", "iphoneappsprogramming.com", "iphoneappsstore.us", "jameseo.com", "jasonberkowitz.com", "johnscamardella.com", "keywordadvertisingedge.com", "keywordspy.com", 
		"kickstartmediagroup.co.uk", "kleinkredit100.de", "kremsoft.com", "krisreid.co", "latestdatabase.com", "lili-marlene-dortmund.de", "listnappend.com", "logodesignsstudio.com", "logodesigntucson.com", 
		"logodesignutah.com", "magnoninternational.com", "makemoneytoday.net", "manektech.com", "marcuseliot.com", "marcuseliott.com", "marketacquisition.com", "marketraise.com", "marvinrussell.com", 
		"marvinrussell.info", "marvinrussellconsultant.com", "marvinrussellphotographer.com", "marvrussell.com", "matthewabolinsseo.com", "mbrussellphotos.us", "meganwritesitdown.com", "mjkmail.in", 
		"mjkmanufacturing.com", "mobileappsprogramming.us", "mpaydayloansa1.info", "multimediaconcepts.nl", "myseoauditor.com", "mysiteauditor.com", "mysmartseo.com", "neednotgreed.org.uk", "negativeseo.link", 
		"netcaremarketing.net", "no-refresh.com", "ocean19.com", "ocean19.net", "ocseo.com", "onesource.com", "onlineadprofessionals.com", "onlineadpros.com", "optimalwebdesign.com.au", "optimisemysite.com", 
		"optimizemysite.com", "optionstradingroom.com", "orange-county-seo.com", "orangelab.in", "own-property.com", "oyctech.com", "oysterr.com", "palmphone.us", "palmphoneprogramming.com", "pattybeni.com", 
		"paydayloanscoolp.co.uk", "paydayloansguy.co.uk", "pb-films.com", "pcltechnology.com", "performsites.com", "petermcdowell.com", "philwebservices.com", "phpdug.net", "pixel2pixel.in", "pliggsubmit.com", 
		"post-comments.com", "probemosjuntos.com", "prudentlabs.in", "quadrantsystems.com", "quickcontent.net", "quillquintessential.com", "ranksdigitalmedia.com", "ranksindia.com", "ranksindia.net", 
		"ranksonic.info", "ravenposter.com", "reidymeister.com", "retailon.biz", "retailon.co", "retailon.co.in", "retailon.in", "retailon.info", "retailon.net", "retailon.org", "retailon.us", "ritwik.com", 
		"rizecorp.com", "rizedigital.com", "rizedigital.com.au", "royalspicehastings.co.uk", "rubyseo.com", "rxiied.com", "ryansheavenlyroofing.blogspot.com", "scuttlesubmitter.com", "searchmediapromotion.in", 
		"searchrankpros.org", "sem-service.com", "semmiami.com", "seo-services-new-york.weebly.com", "seobythehour.com", "seoexplode.com", "seoexplode.us", "seoexponential.com", "seogroup.com", "seogroupie.com", 
		"seoindia.co.in", "seollc.wordpress.com", "seooptimizationtipz.com", "seopagescore.com", "seoranksmart.com", "seoranksmart.net", "seosailor.com", "seoservicesnewyork.org", "seosorcery.in", "seotis.com", 
		"seoutahcounty.com", "seowebbizz.com", "seoxtc.com", "seoxtc.net", "sepgenius.com", "serviciosdeseo.com", "sharefile.com", "shootinginternet.com", "shorttermloans1.tripod.co.uk", "siteaudit1.com", 
		"smart-seo-ranking.com", "snakepaydayloans.co.uk", "socialadsblaster.com", "socialeum.com", "socialmediamarketingxtc.com", "socialobster.com", "softprodigy.com", "softprodigy.in", "softprodigy.net", 
		"softprodigy.us", "softprodigymobile.com", "solarsheild.co.uk", "southrepublik.com", "sowedane-consultants.com", "sparxitsolutions.com", "sparxtechnologies.com", "spencediamonds.com", 
		"splinternetmarketing.com", "splinternetmarketing.net", "splinternetworking.com", "sprinternetmarketing.com", "standardsdownload.co.uk", "stechseo.com", "stepforwardlawncare.com", "strapp.net", 
		"submit-trackback.com", "submitbookmark.com", "sumitseo.com", "superbsocial.net", "swellmarketing.net", "synergita.com", "synergita.net", "tallenzula.in", "techcello.com", "technologus.com", "techpms.com", 
		"techseobiz.com", "techtic.com", "theglobalitsolutions.com", "thehomebusiness.com", "themefuse.com", "themindstudios.com", "theoceanagency.net", "thesagenext.com", "tiffany-howard.com", "tildentasks.com", 
		"transitionwestcliff.org.uk", "triveniinfotech.com", "uberinsider.com", "uberinsiders.com", "usalocalmall.com", "usalocalsearch.com", "usalocalsearch.net", "varshyl.com", "varshylmobile.com", 
		"varshyltech.com", "veltecinfo.com", "ventureplan.com", "vine17.com", "vipsha.com", "viralurl.com", "votreserrurierparis.fr", "vur.me", "watertowncashforgold.com", "webbizzhosting.com", "webbizzindia.com", 
		"webbizzinfosolutions.com", "webdesigncompany.org", "webdesigningfirm.net", "webdesignxtc.com", "webgranth.com", "webmarketingsolutions.info", "webpromotioner.com", "webseomasters.com", "webseostats.com", 
		"webseoxpert.com", "websiteitup.com", "wellnessmn.net", "winemakercellar.com", "winemakersinsider.com", "winemakersrecommend.com", "winerygems.com", "wisconsin-web-designer.com", "wordai.com", 
		"worddumpsterrental.com", "worldaweb.in", "worldtechbuzz.com", "wpromote.com", "writing-web-content.com", "youtube-poster.com", "youtubecommentposterbot.com", "zhfp.net", "zoomtraffics.com", 
		);
	return $blacklist_domains;
	}

function spamshield_get_email_blacklist() {
	$blacklist_emails = array( // 72
		"12345@yahoo.com", "a@a.com", "abey.webworks2@gmail.com", "abey.webworks@gmail.com", "amazingwebdesign01@gmail.com", "andy.roddick63@gmail.com", "anita.developer01@gmail.com", "ankitbusinessseo@gmail.com", 
		"asdf@yahoo.com", "asher.rodrick@gmail.com", "asteor.corp@gmail.com", "brandingcompanyagency@gmail.com", "carmen.philipi@gmail.com", "chan.chawla@gmail.com", "creativewebsolution4you@gmail.com", 
		"digitalexits3@gmail.com", "domain.pri@gmail.com", "donnagabriel04@gmail.com", "enquiries.joomlawebhosting@gmail.com", "erick.magana.sd@gmail.com", "erkn710@yahoo.com", "fredrickparker49@gmail.com", 
		"free.articles.pr.submissions@gmail.com", "fuck@you.com", "hannahandrew259@gmail.com", "himmel@gmail.com", "inventivewebtrack@gmail.com", "jackspencer89@hotmail.com", "jayseopropasal@gmail.com", 
		"jennifer.bdmanager@gmail.com", "johnscamardella@gmail.com", "juliefitzwater@gmail.com", "kellymith4@gmail.com", "kirtiseowebdesigner@gmail.com", "manjupandey882@gmail.com", "marcus.krupp@gmail.com", 
		"matthewabolinsseo@gmail.com", "megan.scussel@gmail.com", "mike.internet1@gmail.com", "mitulcromosys@gmail.com", "mmflaw.com@gmail.com", "monirjibon420@gmail.com", "onlineseobestranking@gmail.com", 
		"oycnow@gmail.com", "prod8055@gmail.com", "ramsevakasociate@gmail.com", "raw_amine@hotmail.fr", "rich.pop11@gmail.com", "roberthansen778@gmail.com", "roberthoot84@gmail.com", "rossmcclelland7@gmail.com", 
		"salessuperseo@gmail.com", "seemaseoindiabizz1@gmail.com", "seematechseobiz@gmail.com", "seobestprise@gmail.com", "seocompany767@gmail.com", "seoenergy11@gmail.com", "seosolution85@gmail.com", 
		"seoxtc@gmail.com", "shivamsms92@gmail.com", "siterankening@gmail.com", "smoseoservicessite@gmail.com", "sudhir.webmaster@gmail.com", "supmondal6@gmail.com", "test@test.com", 
		"thechesterfieldcompany@gmail.com", "toxas1989@gmail.com", "tulikawebdesign@gmail.com", "tvskyshoppers1@gmail.com", "web.neharoy@gmail.com", "webdesingningmarketing@gmail.com", "weblnoida@gmail.com", 
		);
	return $blacklist_emails;
	}

?>