<?php
if ( !function_exists( 'add_action' ) ) {
	if ( !headers_sent() ) { header('HTTP/1.1 403 Forbidden'); }
	die('ERROR: This plugin requires WordPress and will not function if called directly.');
	}

function spamshield_get_anchortxt_blacklist() {
	$blacklist_keyphrases = array( // 1081
		"1 night stand", "1 nite stand", "2013", "2014", "2015", "3 way", "3 way link", "ability", "absolutely", "access", "accident", "account", "accountant", "accounting", "accutane", "acomplia", "acquire", 
		"action", "acupunture", "additional", "address", "adipex", "administration", "adult", "adult chat", "adventure", "advertise", "advertising", "advice", "affiliate", "affliction", "african", "agency", 
		"air jordan", "alabama", "alarm system", "alaska", "allied", "alprostadil", "amateur", "amature", "amazon", "ambassador", "ambien", "analysis", "anchor", "android", "anglomania", "annual", "anonymous", 
		"answer", "antler", "anxiety", "apartment", "appliance", "application", "arcane", "architecture", "arctic", "argent", "arizona", "arkansas", "arterial", "asphalt", "assistant", "attack", "attorney", 
		"auction", "aumento", "australian", "authentic", "availability", "avanafil", "avenue", "average", "aviator", "baccarrat", "bagatelle", "balance", "bamboo", "bandage", "bankruptcy", "baratos", "baseball", 
		"basement", "basketball", "battery", "bed bug", "bedding", "bedroom", "beginner", "behavior", "benefit", "bespoke", "bestiality", "betting", "biggest", "birthday", "bisexual", "blackjack", "blogging", 
		"blogspot", "blow job", "bluetooth", "booster", "booty call", "boulder", "boutique", "bracelet", "brazilian", "bridal", "brigade", "brooch", "browse", "bucuresti", "builder", "building", "bungalow", 
		"burnisher", "business", "buy pill", "cabinet", "caffeine", "calculator", "calendar", "california", "calipers", "call girl", "cambogia", "cannabis", "canvas", "capital", "capture", "car rental", 
		"carisoprodol", "cash advance", "cashmere", "casinos", "casque", "casual", "caterer", "celebrity", "cellulite", "celulit", "century", "certificate", "certify", "challenge", "chat room", "chaturbate", 
		"chaussure", "cheap", "cheat", "chicago", "chicken", "children", "chiropractic", "chiropractor", "chronograph", "cialis", "cigarette", "citrate", "classic", "cleaning", "cleanse", "clear-cut", "clearance", 
		"click here", "click the", "click through", "clinic", "clinical", "clitoris", "clonazepam", "clothes", "clothing", "clutch", "cockroach", "cockroaches", "collection", "college student", "collision", 
		"cologne", "comfortable", "coming", "command", "comment poster", "commentator", "comments", "commercial", "commission", "community", "compact", "compagnie", "company", "compass", "compilation", "compose", 
		"compressed", "compression", "compressor", "computer", "concrete", "condition", "conditioning", "configure", "connecticut", "conservative", "consider", "consolidation", "constructeur", "construction", 
		"consultant", "consulting", "consumption", "content", "contracting", "contractor", "control", "controversy", "convoy", "cooling", "corporate", "cosmetic", "cougar", "counseling", "country", "county", 
		"coupon", "crack", "creator", "credit card", "credit report", "credits", "criminal", "crimson", "cuisine", "cum", "cum shot", "cumulus", "curtain", "custom", "customer", "cutlery", "cyclen", 
		"cyclobenzaprine", "dailymotion", "dapoxetine", "dating", "daughter", "deals", "deduction", "defense", "definition", "delivery", "dental", "dentist", "deodorant", "deposit", "depreciation", "depression", 
		"dermatologist", "descent", "desert", "design", "desnuda", "despicable", "detroit", "deutschland", "development", "diagram", "dictator", "diet pill", "diets", "difference", "different", "digital", "dildo", 
		"diminish", "directly", "directory", "discipline", "discount", "discreet", "disfuncao", "dissertation", "divorce", "domain", "dosage", "download", "drawer", "drawing", "dresses", "dribble", "drug rehab", 
		"drying", "dui lawyer", "dungeon", "durable", "duty free", "dutyfree", "dysfunction", "e-learning", "e-site", "earn money", "economic", "edition", "edmonton", "educational", "effect", "ejaculate", 
		"electrician", "electronic", "elixir", "emergency", "empire", "employment", "enclosure", "energy", "engagement", "engine", "engineer", "engrossar", "enhancement", "enlarged", "enlargement", "enterprise", 
		"entertaining", "entertainment", "enthusiasm", "ephedra", "ephedrine", "equity", "equity loan", "erectile", "erection", "eretil", "erotic", "eroticism", "erythromycin", "escort service", "escorts", 
		"especial", "estate", "european", "evasion", "evolution", "example", "exclusive", "executive", "exercise", "expedition", "experimental", "expert", "exterminating", "extermination", "exterminator", "extract", 
		"extreme", "eyeglasses", "fabric", "facebook", "facial", "factory", "failure", "family", "famous", "fasix", "fat loss", "female", "feminine", "filing", "finance", "financial", "finding", "finishing", 
		"fioricet", "fitness", "flagstaff", "flooring", "follow", "follower", "following", "football", "for sale", "foreclosure", "foreign", "forever", "forex", "forgetfulness", "formal", "formula", "fort worth", 
		"forum", "free code", "freenet", "frontier", "frozen", "fuck", "fuckbuddy", "fuckin", "fundamental", "funeral", "fungal", "furniture", "galaxy", "gambling", "gambling online", "gaming", "garcinia", 
		"garcinia cambogia", "generate", "generation", "generator", "generic", "genesis", "get rid of", "glazing", "government", "gratis", "gratuit", "green coffee", "green tea", "growth", "guarantee", "guarded", 
		"gynecologist", "gynecology", "hack wifi", "hackear", "hair loss", "hand bag", "handle", "hardware", "hawaii", "health", "health care", "healthy", "hearthstone", "heating", "heavenly", "hentai", "herbalife", 
		"herpes", "herself", "heterosexual", "hip hop", "hitherto", "holdem", "holdem poker", "holdem software", "home design", "home equity", "home finance", "homemade", "homeopathic", "homepage", "homosexual", 
		"hormone", "horror", "hospital", "hosting", "hotel", "hotel deal", "hotel e-site", "how to", "hydrocodone", "illinois", "imitation", "immediate", "implant", "impotence", "impotencia", "impotent", "impound", 
		"incest", "income", "independent", "india outsource", "indiana", "indianapolis", "indoor", "infant", "infection", "infestation", "infinity", "information", "inhibitor", "injection", "injury", 
		"injury lawyer", "injustice", "insert", "inspirational", "instagram", "installation", "installer", "instant", "instruct", "instructor", "instrumental", "insult", "insurance", "insurance deal", 
		"insurance quote", "intelligent", "interior", "international", "internet", "interview", "introduction", "invest", "investment", "investor", "irritable", "italian", "jacket", "jacksonville", "jailbreak", 
		"javascript", "jewellery", "jewelry", "jewish", "jockey", "johannesburg", "journalism", "junction", "jungle", "kangaroo", "kentucky", "keratin", "ketone", "keyword", "klonopin", "knives", "kroatien", 
		"kroatien insel brac", "labia", "labial", "labiale", "landlord", "language", "laptop", "laptopuri", "las vegas", "launch", "leading", "lesbian", "leveling", "levelling", "levitra", "levtira", "libido", 
		"library", "lighting", "limited", "link builder", "link building", "linked in", "liquid", "livraison", "location", "locksmith", "logo design", "los angeles", "lose fat", "lose weight", "losing", "lotion", 
		"lottery", "louisiana", "louisville", "luggage", "lunette", "luxury", "lyric", "machine", "magazine", "magnificent", "make money", "making", "management", "manager", "manteau", "manufacturer", "marijuana", 
		"massachusetts", "massage", "masturbate", "material", "mature", "measuring", "medical", "medicament", "medication", "medium", "megapolis", "memphis", "meridia", "message", "metallic", "michigan", "milf", 
		"military", "minnesota", "mississippi", "missouri", "mistake", "mobilabonnement priser", "mobile", "modern", "modernity", "modular", "modulesoft", "momentum", "money make", "monogram", "monster", 
		"montaigne", "monthly", "montre", "mortal", "mortgage", "movie", "moving", "murder", "muscle", "muscular", "naked", "nashville", "natural", "naturally", "nebraska", "necessity", "necklace", "negotiation", 
		"network", "nevada", "new hampshire", "new jersey", "new mexico", "new york", "nike air", "nike shoe", "nimbus", "north carolina", "north dakota", "nude", "nudism", "numerology", "nursery", "ob-gyn", 
		"obstetric", "obstetrician", "occasion", "office", "official", "oklahoma", "one night stand", "one nite stand", "online", "online gambling", "online marketing", "opiate", "opponent", "optimization", 
		"option", "ordering", "organization", "orgasm", "original", "ottawa", "outdoor", "outfit", "outlet", "outsource india", "overnight", "oxymoron", "page rank", "pageant", "painless", "pantry", "particular", 
		"password", "paternity", "pavilion", "paxil", "payday", "pebbled", "penetracion", "penetrate", "peniana", "peniano", "penile", "penis", "pennsylvania", "percocet", "perfectly", "performance", "perfume", 
		"period", "periodontist", "personal", "personalization", "pest control", "petroleum", "phantom", "pharmacy", "phentermine", "philadelphia", "photoshop", "php expert", "phpdug", "phytoceramide", "pills", 
		"pinterest", "pirate", "plague", "plan cul", "plan q", "planet", "plantar fasciitis", "plastic", "platinum", "play", "plumbing", "poker", "poker chip", "policy", "politic", "political", "pompano", "popular", 
		"population", "porn", "porn star", "porno", "pornographic", "pornography", "porntube", "portable", "portfolio", "possible", "power kite", "poze", "practice", "pregnancy", "pregnant", "prelude", "premature", 
		"premium", "prepaid", "prescription", "press room", "pressure", "prestige", "prevent", "previous", "priligy", "primary", "princess", "prisoner", "private", "product", "production", "professional", "program", 
		"programa", "programme", "project", "promo code", "promotion", "propane", "propecia", "property", "proportional", "prostate", "prostitute", "protein", "protocol", "proxy", "psychic", "publicity", 
		"pulmonary", "purse", "pussy", "quartz", "quote", "racing", "ranking", "rapes", "raping", "rapist", "reaction", "read the", "realistic", "reality", "realty", "recent", "recruiting", "redeem", "redsnow", 
		"reduce", "reebok", "reference", "reflection", "reflective", "reflexion", "refrigerator", "relate", "related", "release", "religion", "removal", "remove", "rencontre", "renewal", "renovating", "renovation", 
		"rent a car", "rental", "repair", "reparatii", "repellent", "replace", "replacement", "replica", "replicate", "reputation", "requin", "residence", "residential", "resource", "restaurant", "restoration", 
		"restore", "result", "return", "revatio", "reverse", "reviews", "rhinoplasty", "rhode island", "rimonabant", "ring tone", "ripped", "rivotril", "roaches", "roofer", "roofing", "router", "runway", "safety", 
		"san antonio", "san diego", "san francisco", "san jose", "satellite", "saturday", "schedule", "search engine", "search marketing", "seattle", "secondary", "secret", "secure", "security", "segment", "sem", 
		"seminar", "sempre", "sensible", "sensitive", "seo", "septum", "series", "services", "sex", "sex drive", "sex tape", "sexcam", "sexe", "sexiness", "sexism", "sexologia", "sextant", "sexual", 
		"sexual performance", "sexual service", "sexuality", "sexy", "shades", "shampoo", "shemale", "shipping", "shoes", "shopping", "short-term loan", "showroom", "sildenafil", "simply", "simulation", "sister", 
		"sizing", "skater", "skeleton", "sketch", "skin care", "sleeve", "slot machine", "smoking", "sneaker", "soccer", "social", "social bookmark", "social media", "social poster", "social submitter", "society", 
		"software", "solenoid", "soma", "source", "south carolina", "south dakota", "special", "spence diamond", "spinal", "splashy", "spray tan", "stainless", "starcraft", "starting", "statement", "statistics", 
		"staxyn", "stendra", "steroid", "storify", "straightforward", "streaming", "student loan", "stylish", "submitter", "success", "suggestion", "sunglass", "sunglasses", "supplement", "supply", "support", 
		"surgeons", "surgery", "survey", "survival", "swatch", "sweating", "syndrome", "system", "tablet", "tactic", "tadalafil", "taille", "tanning", "tassel", "technology", "template", "temporary", "tequila", 
		"testosterone", "texas holdem", "thanksgiving", "therapy", "thousand", "three way", "three way link", "through", "title", "toddler", "toilette", "top e-site", "top site", "tortoise", "trackback", "tractor", 
		"trading", "traffic", "training", "tramadol", "transfer", "translate", "transportation", "travail", "travel", "treatment", "trim spa", "tropical", "troubleshoot", "troubleshooting", "turbo tax", "turnkey", 
		"turquoise", "tutorial", "twitter", "tycoon", "ultimate", "ultram", "unblocked", "underground", "underneath", "understanding", "underwear", "unique", "unisex", "united states", "university", "unlimited", 
		"unlock", "uptown", "utility", "vacation", "vagina", "vaginal", "valium", "vancouver", "vardenafil", "various", "vehicle", "ventilation", "veterinarian", "veterinary", "viagra", "video", "videography", 
		"vigara", "vigrx", "village", "vintage", "vioxx", "vision", "visit", "visit now", "visual", "volume", "vortex", "voucher", "voyage", "warfare", "watches", "waterproof", "wayfarer", "wealth", "web host", 
		"web hosting", "web page", "web site", "webmaster", "weight loss", "weightless", "west virginia", "whirlpool", "whitening", "wholesale", "wicked", "wifi hack", "wifi hacker", "window", "wireless", 
		"wisconsin", "work out", "wrestling", "writing service", "wyoming", "xanax", "xenical", "xxx", "youtube", "zimulti", "zithromax", "zoekmachine optimalisatie", "zolus", 
		);
	return $blacklist_keyphrases;
	}
?>